# Generated by Django 6.0.2 on 2026-03-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_app', '0002_rename_current_status_profile_current_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='instagram_id',
        ),
    ]
