# Generated by Django 6.0.2 on 2026-04-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_app', '0003_remove_profile_instagram_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
