# Generated by Django 6.0.2 on 2026-02-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_app', '0003_job_company_job_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
