# Generated by Django 6.0.2 on 2026-02-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_app', '0006_remove_job_image_url_remove_job_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('alumni', 'Alumni')], default='alumni', max_length=10),
        ),
    ]
