# Generated by Django 6.0.2 on 2026-02-17 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_app', '0008_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
