# Generated by Django 6.0.2 on 2026-02-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_app', '0010_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('Website', 'Website'), ('Events', 'Events'), ('Jobs', 'Jobs'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
