# Generated by Django 6.0.2 on 2026-02-18 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_app', '0011_feedback_admin_reply_feedback_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='admin_reply',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='category',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
    ]
