# Generated by Django 6.0.2 on 2026-02-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_app', '0013_rename_current_status_profile_current_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='appointment_order',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='proof_id',
            field=models.FileField(blank=True, null=True, upload_to='id'),
        ),
    ]
