# Generated by Django 6.0.2 on 2026-03-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_app', '0015_feedback_name_alter_feedback_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_id_image',
            field=models.FileField(blank=True, null=True, upload_to='company_id/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='google_scholar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='appointment_order',
            field=models.FileField(blank=True, null=True, upload_to='appointment_orders/'),
        ),
    ]
