# Generated by Django 6.0.2 on 2026-03-15 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_app', '0016_profile_company_id_image_profile_google_scholar_and_more'),
        ('Alumni_app', '0016_profile_created_at'),
    ]

    operations = [
    ]
