# Generated by Django 6.0.2 on 2026-03-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_app', '0016_profile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_id',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='google_scholar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_id',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linked_in',
            field=models.URLField(blank=True, null=True),
        ),
    ]
