# Generated by Django 6.0.2 on 2026-03-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_app', '0017_merge_20260315_2121'),
        ('Alumni_app', '0017_profile_company_id_profile_google_scholar_and_more'),
    ]

    operations = [
    ]
